/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as InstallRouteImport } from './routes/install'
import { Route as AppActivitiesRouteImport } from './routes/_app/activities'
import { Route as AppActivityTimelineRouteImport } from './routes/_app/activity-timeline'
import { Route as AppActivityTypesRouteImport } from './routes/_app/activity-types'
import { Route as AppAdminControlsRouteImport } from './routes/_app/admin-controls'
import { Route as AppAnalyticsRouteImport } from './routes/_app/analytics'
import { Route as AppAttendanceRouteImport } from './routes/_app/attendance'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppExpensesRouteImport } from './routes/_app/expenses'
import { Route as AppGpsTrackingRouteImport } from './routes/_app/gps-tracking'
import { Route as AppMoreRouteImport } from './routes/_app/more'
import { Route as AppMyTeamRouteImport } from './routes/_app/my-team'
import { Route as AppNotificationsRouteImport } from './routes/_app/notifications'
import { Route as AppPendingApprovalsRouteImport } from './routes/_app/pending-approvals'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppSitesRouteImport } from './routes/_app/sites'
import { Route as AppVisitsRouteImport } from './routes/_app/visits'
import { Route as AppAdminIndexRouteImport } from './routes/_app/admin/index'
import { Route as AppAdminActivityTypesRouteImport } from './routes/_app/admin/activity-types'
import { Route as AppAdminAttendanceRouteImport } from './routes/_app/admin/attendance'
import { Route as AppAdminCompanyRouteImport } from './routes/_app/admin/company'
import { Route as AppAdminConfigurationRouteImport } from './routes/_app/admin/configuration'
import { Route as AppAdminExpensesRouteImport } from './routes/_app/admin/expenses'
import { Route as AppAdminNotificationRulesRouteImport } from './routes/_app/admin/notification-rules'
import { Route as AppAdminSecurityRouteImport } from './routes/_app/admin/security'
import { Route as AppAdminSitesRouteImport } from './routes/_app/admin/sites'
import { Route as AppAdminUsersRouteImport } from './routes/_app/admin/users'
import { Route as AppEventsIndexRouteImport } from './routes/_app/events/index'
import { Route as AppEventsIdRouteImport } from './routes/_app/events/$id'
import { Route as AppLeadsEventsIndexRouteImport } from './routes/_app/leads-events/index'
import { Route as AppLeadsIndexRouteImport } from './routes/_app/leads/index'
import { Route as AppLeadsIdRouteImport } from './routes/_app/leads/$id'
import { Route as AppMasterDataIndexRouteImport } from './routes/_app/master-data/index'
import { Route as AppMasterDataActivityOutcomesRouteImport } from './routes/_app/master-data/activity-outcomes'
import { Route as AppMasterDataAddressesRouteImport } from './routes/_app/master-data/addresses'
import { Route as AppMasterDataCategoriesRouteImport } from './routes/_app/master-data/categories'
import { Route as AppMasterDataCurrenciesRouteImport } from './routes/_app/master-data/currencies'
import { Route as AppMasterDataEventTypesRouteImport } from './routes/_app/master-data/event-types'
import { Route as AppMasterDataIndustriesRouteImport } from './routes/_app/master-data/industries'
import { Route as AppMasterDataLeadScoringRouteImport } from './routes/_app/master-data/lead-scoring'
import { Route as AppMasterDataLeadSourcesRouteImport } from './routes/_app/master-data/lead-sources'
import { Route as AppMasterDataLeadStatusesRouteImport } from './routes/_app/master-data/lead-statuses'
import { Route as AppMasterDataOpportunityScoringRouteImport } from './routes/_app/master-data/opportunity-scoring'
import { Route as AppMasterDataOpportunityStagesRouteImport } from './routes/_app/master-data/opportunity-stages'
import { Route as AppMasterDataOpportunityTypesRouteImport } from './routes/_app/master-data/opportunity-types'
import { Route as AppMasterDataPaymentTermsRouteImport } from './routes/_app/master-data/payment-terms'
import { Route as AppMasterDataProductsRouteImport } from './routes/_app/master-data/products'
import { Route as AppMasterDataUomRouteImport } from './routes/_app/master-data/uom'
import { Route as AppProjectsIndexRouteImport } from './routes/_app/projects/index'
import { Route as AppProjectsIdRouteImport } from './routes/_app/projects/$id'
import { Route as AppReportsIndexRouteImport } from './routes/_app/reports/index'
import { Route as AppReportsTypeRouteImport } from './routes/_app/reports/$type'
import { Route as AppTemplatesIndexRouteImport } from './routes/_app/templates/index'
import { Route as AppTemplatesIdRouteImport } from './routes/_app/templates/$id'
import { Route as AppVendorsIdRouteImport } from './routes/_app/vendors/$id'
import { Route as AppLeadsEventsEventsIdRouteImport } from './routes/_app/leads-events/events/$id'
import { Route as AppLeadsEventsLeadsIdRouteImport } from './routes/_app/leads-events/leads/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallRoute = InstallRouteImport.update({
  id: '/install',
  path: '/install',
  getParentRoute: () => rootRouteImport,
} as any)
const AppActivitiesRoute = AppActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => AppRoute,
} as any)
const AppActivityTimelineRoute = AppActivityTimelineRouteImport.update({
  id: '/activity-timeline',
  path: '/activity-timeline',
  getParentRoute: () => AppRoute,
} as any)
const AppActivityTypesRoute = AppActivityTypesRouteImport.update({
  id: '/activity-types',
  path: '/activity-types',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminControlsRoute = AppAdminControlsRouteImport.update({
  id: '/admin-controls',
  path: '/admin-controls',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppAttendanceRoute = AppAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppExpensesRoute = AppExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AppRoute,
} as any)
const AppGpsTrackingRoute = AppGpsTrackingRouteImport.update({
  id: '/gps-tracking',
  path: '/gps-tracking',
  getParentRoute: () => AppRoute,
} as any)
const AppMoreRoute = AppMoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => AppRoute,
} as any)
const AppMyTeamRoute = AppMyTeamRouteImport.update({
  id: '/my-team',
  path: '/my-team',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppPendingApprovalsRoute = AppPendingApprovalsRouteImport.update({
  id: '/pending-approvals',
  path: '/pending-approvals',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppSitesRoute = AppSitesRouteImport.update({
  id: '/sites',
  path: '/sites',
  getParentRoute: () => AppRoute,
} as any)
const AppVisitsRoute = AppVisitsRouteImport.update({
  id: '/visits',
  path: '/visits',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminActivityTypesRoute = AppAdminActivityTypesRouteImport.update({
  id: '/admin/activity-types',
  path: '/admin/activity-types',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminAttendanceRoute = AppAdminAttendanceRouteImport.update({
  id: '/admin/attendance',
  path: '/admin/attendance',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminCompanyRoute = AppAdminCompanyRouteImport.update({
  id: '/admin/company',
  path: '/admin/company',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminConfigurationRoute = AppAdminConfigurationRouteImport.update({
  id: '/admin/configuration',
  path: '/admin/configuration',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminExpensesRoute = AppAdminExpensesRouteImport.update({
  id: '/admin/expenses',
  path: '/admin/expenses',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminNotificationRulesRoute =
  AppAdminNotificationRulesRouteImport.update({
    id: '/admin/notification-rules',
    path: '/admin/notification-rules',
    getParentRoute: () => AppRoute,
  } as any)
const AppAdminSecurityRoute = AppAdminSecurityRouteImport.update({
  id: '/admin/security',
  path: '/admin/security',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminSitesRoute = AppAdminSitesRouteImport.update({
  id: '/admin/sites',
  path: '/admin/sites',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AppRoute,
} as any)
const AppEventsIndexRoute = AppEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => AppRoute,
} as any)
const AppEventsIdRoute = AppEventsIdRouteImport.update({
  id: '/events/$id',
  path: '/events/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadsEventsIndexRoute = AppLeadsEventsIndexRouteImport.update({
  id: '/leads-events/',
  path: '/leads-events/',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadsIndexRoute = AppLeadsIndexRouteImport.update({
  id: '/leads/',
  path: '/leads/',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadsIdRoute = AppLeadsIdRouteImport.update({
  id: '/leads/$id',
  path: '/leads/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppMasterDataIndexRoute = AppMasterDataIndexRouteImport.update({
  id: '/master-data/',
  path: '/master-data/',
  getParentRoute: () => AppRoute,
} as any)
const AppMasterDataActivityOutcomesRoute =
  AppMasterDataActivityOutcomesRouteImport.update({
    id: '/master-data/activity-outcomes',
    path: '/master-data/activity-outcomes',
    getParentRoute: () => AppRoute,
  } as any)
const AppMasterDataAddressesRoute = AppMasterDataAddressesRouteImport.update({
  id: '/master-data/addresses',
  path: '/master-data/addresses',
  getParentRoute: () => AppRoute,
} as any)
const AppMasterDataCategoriesRoute = AppMasterDataCategoriesRouteImport.update({
  id: '/master-data/categories',
  path: '/master-data/categories',
  getParentRoute: () => AppRoute,
} as any)
const AppMasterDataCurrenciesRoute = AppMasterDataCurrenciesRouteImport.update({
  id: '/master-data/currencies',
  path: '/master-data/currencies',
  getParentRoute: () => AppRoute,
} as any)
const AppMasterDataEventTypesRoute = AppMasterDataEventTypesRouteImport.update({
  id: '/master-data/event-types',
  path: '/master-data/event-types',
  getParentRoute: () => AppRoute,
} as any)
const AppMasterDataIndustriesRoute = AppMasterDataIndustriesRouteImport.update({
  id: '/master-data/industries',
  path: '/master-data/industries',
  getParentRoute: () => AppRoute,
} as any)
const AppMasterDataLeadScoringRoute =
  AppMasterDataLeadScoringRouteImport.update({
    id: '/master-data/lead-scoring',
    path: '/master-data/lead-scoring',
    getParentRoute: () => AppRoute,
  } as any)
const AppMasterDataLeadSourcesRoute =
  AppMasterDataLeadSourcesRouteImport.update({
    id: '/master-data/lead-sources',
    path: '/master-data/lead-sources',
    getParentRoute: () => AppRoute,
  } as any)
const AppMasterDataLeadStatusesRoute =
  AppMasterDataLeadStatusesRouteImport.update({
    id: '/master-data/lead-statuses',
    path: '/master-data/lead-statuses',
    getParentRoute: () => AppRoute,
  } as any)
const AppMasterDataOpportunityScoringRoute =
  AppMasterDataOpportunityScoringRouteImport.update({
    id: '/master-data/opportunity-scoring',
    path: '/master-data/opportunity-scoring',
    getParentRoute: () => AppRoute,
  } as any)
const AppMasterDataOpportunityStagesRoute =
  AppMasterDataOpportunityStagesRouteImport.update({
    id: '/master-data/opportunity-stages',
    path: '/master-data/opportunity-stages',
    getParentRoute: () => AppRoute,
  } as any)
const AppMasterDataOpportunityTypesRoute =
  AppMasterDataOpportunityTypesRouteImport.update({
    id: '/master-data/opportunity-types',
    path: '/master-data/opportunity-types',
    getParentRoute: () => AppRoute,
  } as any)
const AppMasterDataPaymentTermsRoute =
  AppMasterDataPaymentTermsRouteImport.update({
    id: '/master-data/payment-terms',
    path: '/master-data/payment-terms',
    getParentRoute: () => AppRoute,
  } as any)
const AppMasterDataProductsRoute = AppMasterDataProductsRouteImport.update({
  id: '/master-data/products',
  path: '/master-data/products',
  getParentRoute: () => AppRoute,
} as any)
const AppMasterDataUomRoute = AppMasterDataUomRouteImport.update({
  id: '/master-data/uom',
  path: '/master-data/uom',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsIndexRoute = AppProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsIdRoute = AppProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsIndexRoute = AppReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsTypeRoute = AppReportsTypeRouteImport.update({
  id: '/reports/$type',
  path: '/reports/$type',
  getParentRoute: () => AppRoute,
} as any)
const AppTemplatesIndexRoute = AppTemplatesIndexRouteImport.update({
  id: '/templates/',
  path: '/templates/',
  getParentRoute: () => AppRoute,
} as any)
const AppTemplatesIdRoute = AppTemplatesIdRouteImport.update({
  id: '/templates/$id',
  path: '/templates/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppVendorsIdRoute = AppVendorsIdRouteImport.update({
  id: '/vendors/$id',
  path: '/vendors/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadsEventsEventsIdRoute = AppLeadsEventsEventsIdRouteImport.update({
  id: '/leads-events/events/$id',
  path: '/leads-events/events/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadsEventsLeadsIdRoute = AppLeadsEventsLeadsIdRouteImport.update({
  id: '/leads-events/leads/$id',
  path: '/leads-events/leads/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/install': typeof InstallRoute
  '/activities': typeof AppActivitiesRoute
  '/activity-timeline': typeof AppActivityTimelineRoute
  '/activity-types': typeof AppActivityTypesRoute
  '/admin-controls': typeof AppAdminControlsRoute
  '/analytics': typeof AppAnalyticsRoute
  '/attendance': typeof AppAttendanceRoute
  '/dashboard': typeof AppDashboardRoute
  '/expenses': typeof AppExpensesRoute
  '/gps-tracking': typeof AppGpsTrackingRoute
  '/more': typeof AppMoreRoute
  '/my-team': typeof AppMyTeamRoute
  '/notifications': typeof AppNotificationsRoute
  '/pending-approvals': typeof AppPendingApprovalsRoute
  '/profile': typeof AppProfileRoute
  '/sites': typeof AppSitesRoute
  '/visits': typeof AppVisitsRoute
  '/admin/activity-types': typeof AppAdminActivityTypesRoute
  '/admin/attendance': typeof AppAdminAttendanceRoute
  '/admin/company': typeof AppAdminCompanyRoute
  '/admin/configuration': typeof AppAdminConfigurationRoute
  '/admin/expenses': typeof AppAdminExpensesRoute
  '/admin/notification-rules': typeof AppAdminNotificationRulesRoute
  '/admin/security': typeof AppAdminSecurityRoute
  '/admin/sites': typeof AppAdminSitesRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/events/$id': typeof AppEventsIdRoute
  '/leads/$id': typeof AppLeadsIdRoute
  '/master-data/activity-outcomes': typeof AppMasterDataActivityOutcomesRoute
  '/master-data/addresses': typeof AppMasterDataAddressesRoute
  '/master-data/categories': typeof AppMasterDataCategoriesRoute
  '/master-data/currencies': typeof AppMasterDataCurrenciesRoute
  '/master-data/event-types': typeof AppMasterDataEventTypesRoute
  '/master-data/industries': typeof AppMasterDataIndustriesRoute
  '/master-data/lead-scoring': typeof AppMasterDataLeadScoringRoute
  '/master-data/lead-sources': typeof AppMasterDataLeadSourcesRoute
  '/master-data/lead-statuses': typeof AppMasterDataLeadStatusesRoute
  '/master-data/opportunity-scoring': typeof AppMasterDataOpportunityScoringRoute
  '/master-data/opportunity-stages': typeof AppMasterDataOpportunityStagesRoute
  '/master-data/opportunity-types': typeof AppMasterDataOpportunityTypesRoute
  '/master-data/payment-terms': typeof AppMasterDataPaymentTermsRoute
  '/master-data/products': typeof AppMasterDataProductsRoute
  '/master-data/uom': typeof AppMasterDataUomRoute
  '/projects/$id': typeof AppProjectsIdRoute
  '/reports/$type': typeof AppReportsTypeRoute
  '/templates/$id': typeof AppTemplatesIdRoute
  '/vendors/$id': typeof AppVendorsIdRoute
  '/admin/': typeof AppAdminIndexRoute
  '/events/': typeof AppEventsIndexRoute
  '/leads-events/': typeof AppLeadsEventsIndexRoute
  '/leads/': typeof AppLeadsIndexRoute
  '/master-data/': typeof AppMasterDataIndexRoute
  '/projects/': typeof AppProjectsIndexRoute
  '/reports/': typeof AppReportsIndexRoute
  '/templates/': typeof AppTemplatesIndexRoute
  '/leads-events/events/$id': typeof AppLeadsEventsEventsIdRoute
  '/leads-events/leads/$id': typeof AppLeadsEventsLeadsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/install': typeof InstallRoute
  '/activities': typeof AppActivitiesRoute
  '/activity-timeline': typeof AppActivityTimelineRoute
  '/activity-types': typeof AppActivityTypesRoute
  '/admin-controls': typeof AppAdminControlsRoute
  '/analytics': typeof AppAnalyticsRoute
  '/attendance': typeof AppAttendanceRoute
  '/dashboard': typeof AppDashboardRoute
  '/expenses': typeof AppExpensesRoute
  '/gps-tracking': typeof AppGpsTrackingRoute
  '/more': typeof AppMoreRoute
  '/my-team': typeof AppMyTeamRoute
  '/notifications': typeof AppNotificationsRoute
  '/pending-approvals': typeof AppPendingApprovalsRoute
  '/profile': typeof AppProfileRoute
  '/sites': typeof AppSitesRoute
  '/visits': typeof AppVisitsRoute
  '/admin/activity-types': typeof AppAdminActivityTypesRoute
  '/admin/attendance': typeof AppAdminAttendanceRoute
  '/admin/company': typeof AppAdminCompanyRoute
  '/admin/configuration': typeof AppAdminConfigurationRoute
  '/admin/expenses': typeof AppAdminExpensesRoute
  '/admin/notification-rules': typeof AppAdminNotificationRulesRoute
  '/admin/security': typeof AppAdminSecurityRoute
  '/admin/sites': typeof AppAdminSitesRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/events/$id': typeof AppEventsIdRoute
  '/leads/$id': typeof AppLeadsIdRoute
  '/master-data/activity-outcomes': typeof AppMasterDataActivityOutcomesRoute
  '/master-data/addresses': typeof AppMasterDataAddressesRoute
  '/master-data/categories': typeof AppMasterDataCategoriesRoute
  '/master-data/currencies': typeof AppMasterDataCurrenciesRoute
  '/master-data/event-types': typeof AppMasterDataEventTypesRoute
  '/master-data/industries': typeof AppMasterDataIndustriesRoute
  '/master-data/lead-scoring': typeof AppMasterDataLeadScoringRoute
  '/master-data/lead-sources': typeof AppMasterDataLeadSourcesRoute
  '/master-data/lead-statuses': typeof AppMasterDataLeadStatusesRoute
  '/master-data/opportunity-scoring': typeof AppMasterDataOpportunityScoringRoute
  '/master-data/opportunity-stages': typeof AppMasterDataOpportunityStagesRoute
  '/master-data/opportunity-types': typeof AppMasterDataOpportunityTypesRoute
  '/master-data/payment-terms': typeof AppMasterDataPaymentTermsRoute
  '/master-data/products': typeof AppMasterDataProductsRoute
  '/master-data/uom': typeof AppMasterDataUomRoute
  '/projects/$id': typeof AppProjectsIdRoute
  '/reports/$type': typeof AppReportsTypeRoute
  '/templates/$id': typeof AppTemplatesIdRoute
  '/vendors/$id': typeof AppVendorsIdRoute
  '/admin': typeof AppAdminIndexRoute
  '/events': typeof AppEventsIndexRoute
  '/leads-events': typeof AppLeadsEventsIndexRoute
  '/leads': typeof AppLeadsIndexRoute
  '/master-data': typeof AppMasterDataIndexRoute
  '/projects': typeof AppProjectsIndexRoute
  '/reports': typeof AppReportsIndexRoute
  '/templates': typeof AppTemplatesIndexRoute
  '/leads-events/events/$id': typeof AppLeadsEventsEventsIdRoute
  '/leads-events/leads/$id': typeof AppLeadsEventsLeadsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/install': typeof InstallRoute
  '/_app/activities': typeof AppActivitiesRoute
  '/_app/activity-timeline': typeof AppActivityTimelineRoute
  '/_app/activity-types': typeof AppActivityTypesRoute
  '/_app/admin-controls': typeof AppAdminControlsRoute
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/attendance': typeof AppAttendanceRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/expenses': typeof AppExpensesRoute
  '/_app/gps-tracking': typeof AppGpsTrackingRoute
  '/_app/more': typeof AppMoreRoute
  '/_app/my-team': typeof AppMyTeamRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/pending-approvals': typeof AppPendingApprovalsRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/sites': typeof AppSitesRoute
  '/_app/visits': typeof AppVisitsRoute
  '/_app/admin/activity-types': typeof AppAdminActivityTypesRoute
  '/_app/admin/attendance': typeof AppAdminAttendanceRoute
  '/_app/admin/company': typeof AppAdminCompanyRoute
  '/_app/admin/configuration': typeof AppAdminConfigurationRoute
  '/_app/admin/expenses': typeof AppAdminExpensesRoute
  '/_app/admin/notification-rules': typeof AppAdminNotificationRulesRoute
  '/_app/admin/security': typeof AppAdminSecurityRoute
  '/_app/admin/sites': typeof AppAdminSitesRoute
  '/_app/admin/users': typeof AppAdminUsersRoute
  '/_app/events/$id': typeof AppEventsIdRoute
  '/_app/leads/$id': typeof AppLeadsIdRoute
  '/_app/master-data/activity-outcomes': typeof AppMasterDataActivityOutcomesRoute
  '/_app/master-data/addresses': typeof AppMasterDataAddressesRoute
  '/_app/master-data/categories': typeof AppMasterDataCategoriesRoute
  '/_app/master-data/currencies': typeof AppMasterDataCurrenciesRoute
  '/_app/master-data/event-types': typeof AppMasterDataEventTypesRoute
  '/_app/master-data/industries': typeof AppMasterDataIndustriesRoute
  '/_app/master-data/lead-scoring': typeof AppMasterDataLeadScoringRoute
  '/_app/master-data/lead-sources': typeof AppMasterDataLeadSourcesRoute
  '/_app/master-data/lead-statuses': typeof AppMasterDataLeadStatusesRoute
  '/_app/master-data/opportunity-scoring': typeof AppMasterDataOpportunityScoringRoute
  '/_app/master-data/opportunity-stages': typeof AppMasterDataOpportunityStagesRoute
  '/_app/master-data/opportunity-types': typeof AppMasterDataOpportunityTypesRoute
  '/_app/master-data/payment-terms': typeof AppMasterDataPaymentTermsRoute
  '/_app/master-data/products': typeof AppMasterDataProductsRoute
  '/_app/master-data/uom': typeof AppMasterDataUomRoute
  '/_app/projects/$id': typeof AppProjectsIdRoute
  '/_app/reports/$type': typeof AppReportsTypeRoute
  '/_app/templates/$id': typeof AppTemplatesIdRoute
  '/_app/vendors/$id': typeof AppVendorsIdRoute
  '/_app/admin/': typeof AppAdminIndexRoute
  '/_app/events/': typeof AppEventsIndexRoute
  '/_app/leads-events/': typeof AppLeadsEventsIndexRoute
  '/_app/leads/': typeof AppLeadsIndexRoute
  '/_app/master-data/': typeof AppMasterDataIndexRoute
  '/_app/projects/': typeof AppProjectsIndexRoute
  '/_app/reports/': typeof AppReportsIndexRoute
  '/_app/templates/': typeof AppTemplatesIndexRoute
  '/_app/leads-events/events/$id': typeof AppLeadsEventsEventsIdRoute
  '/_app/leads-events/leads/$id': typeof AppLeadsEventsLeadsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/install'
    | '/activities'
    | '/activity-timeline'
    | '/activity-types'
    | '/admin-controls'
    | '/analytics'
    | '/attendance'
    | '/dashboard'
    | '/expenses'
    | '/gps-tracking'
    | '/more'
    | '/my-team'
    | '/notifications'
    | '/pending-approvals'
    | '/profile'
    | '/sites'
    | '/visits'
    | '/admin/activity-types'
    | '/admin/attendance'
    | '/admin/company'
    | '/admin/configuration'
    | '/admin/expenses'
    | '/admin/notification-rules'
    | '/admin/security'
    | '/admin/sites'
    | '/admin/users'
    | '/events/$id'
    | '/leads/$id'
    | '/master-data/activity-outcomes'
    | '/master-data/addresses'
    | '/master-data/categories'
    | '/master-data/currencies'
    | '/master-data/event-types'
    | '/master-data/industries'
    | '/master-data/lead-scoring'
    | '/master-data/lead-sources'
    | '/master-data/lead-statuses'
    | '/master-data/opportunity-scoring'
    | '/master-data/opportunity-stages'
    | '/master-data/opportunity-types'
    | '/master-data/payment-terms'
    | '/master-data/products'
    | '/master-data/uom'
    | '/projects/$id'
    | '/reports/$type'
    | '/templates/$id'
    | '/vendors/$id'
    | '/admin/'
    | '/events/'
    | '/leads-events/'
    | '/leads/'
    | '/master-data/'
    | '/projects/'
    | '/reports/'
    | '/templates/'
    | '/leads-events/events/$id'
    | '/leads-events/leads/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/install'
    | '/activities'
    | '/activity-timeline'
    | '/activity-types'
    | '/admin-controls'
    | '/analytics'
    | '/attendance'
    | '/dashboard'
    | '/expenses'
    | '/gps-tracking'
    | '/more'
    | '/my-team'
    | '/notifications'
    | '/pending-approvals'
    | '/profile'
    | '/sites'
    | '/visits'
    | '/admin/activity-types'
    | '/admin/attendance'
    | '/admin/company'
    | '/admin/configuration'
    | '/admin/expenses'
    | '/admin/notification-rules'
    | '/admin/security'
    | '/admin/sites'
    | '/admin/users'
    | '/events/$id'
    | '/leads/$id'
    | '/master-data/activity-outcomes'
    | '/master-data/addresses'
    | '/master-data/categories'
    | '/master-data/currencies'
    | '/master-data/event-types'
    | '/master-data/industries'
    | '/master-data/lead-scoring'
    | '/master-data/lead-sources'
    | '/master-data/lead-statuses'
    | '/master-data/opportunity-scoring'
    | '/master-data/opportunity-stages'
    | '/master-data/opportunity-types'
    | '/master-data/payment-terms'
    | '/master-data/products'
    | '/master-data/uom'
    | '/projects/$id'
    | '/reports/$type'
    | '/templates/$id'
    | '/vendors/$id'
    | '/admin'
    | '/events'
    | '/leads-events'
    | '/leads'
    | '/master-data'
    | '/projects'
    | '/reports'
    | '/templates'
    | '/leads-events/events/$id'
    | '/leads-events/leads/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/install'
    | '/_app/activities'
    | '/_app/activity-timeline'
    | '/_app/activity-types'
    | '/_app/admin-controls'
    | '/_app/analytics'
    | '/_app/attendance'
    | '/_app/dashboard'
    | '/_app/expenses'
    | '/_app/gps-tracking'
    | '/_app/more'
    | '/_app/my-team'
    | '/_app/notifications'
    | '/_app/pending-approvals'
    | '/_app/profile'
    | '/_app/sites'
    | '/_app/visits'
    | '/_app/admin/activity-types'
    | '/_app/admin/attendance'
    | '/_app/admin/company'
    | '/_app/admin/configuration'
    | '/_app/admin/expenses'
    | '/_app/admin/notification-rules'
    | '/_app/admin/security'
    | '/_app/admin/sites'
    | '/_app/admin/users'
    | '/_app/events/$id'
    | '/_app/leads/$id'
    | '/_app/master-data/activity-outcomes'
    | '/_app/master-data/addresses'
    | '/_app/master-data/categories'
    | '/_app/master-data/currencies'
    | '/_app/master-data/event-types'
    | '/_app/master-data/industries'
    | '/_app/master-data/lead-scoring'
    | '/_app/master-data/lead-sources'
    | '/_app/master-data/lead-statuses'
    | '/_app/master-data/opportunity-scoring'
    | '/_app/master-data/opportunity-stages'
    | '/_app/master-data/opportunity-types'
    | '/_app/master-data/payment-terms'
    | '/_app/master-data/products'
    | '/_app/master-data/uom'
    | '/_app/projects/$id'
    | '/_app/reports/$type'
    | '/_app/templates/$id'
    | '/_app/vendors/$id'
    | '/_app/admin/'
    | '/_app/events/'
    | '/_app/leads-events/'
    | '/_app/leads/'
    | '/_app/master-data/'
    | '/_app/projects/'
    | '/_app/reports/'
    | '/_app/templates/'
    | '/_app/leads-events/events/$id'
    | '/_app/leads-events/leads/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  InstallRoute: typeof InstallRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/install': {
      id: '/install'
      path: '/install'
      fullPath: '/install'
      preLoaderRoute: typeof InstallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/activities': {
      id: '/_app/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof AppActivitiesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/activity-timeline': {
      id: '/_app/activity-timeline'
      path: '/activity-timeline'
      fullPath: '/activity-timeline'
      preLoaderRoute: typeof AppActivityTimelineRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/activity-types': {
      id: '/_app/activity-types'
      path: '/activity-types'
      fullPath: '/activity-types'
      preLoaderRoute: typeof AppActivityTypesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin-controls': {
      id: '/_app/admin-controls'
      path: '/admin-controls'
      fullPath: '/admin-controls'
      preLoaderRoute: typeof AppAdminControlsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/attendance': {
      id: '/_app/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AppAttendanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/expenses': {
      id: '/_app/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof AppExpensesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/gps-tracking': {
      id: '/_app/gps-tracking'
      path: '/gps-tracking'
      fullPath: '/gps-tracking'
      preLoaderRoute: typeof AppGpsTrackingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/more': {
      id: '/_app/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof AppMoreRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/my-team': {
      id: '/_app/my-team'
      path: '/my-team'
      fullPath: '/my-team'
      preLoaderRoute: typeof AppMyTeamRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pending-approvals': {
      id: '/_app/pending-approvals'
      path: '/pending-approvals'
      fullPath: '/pending-approvals'
      preLoaderRoute: typeof AppPendingApprovalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sites': {
      id: '/_app/sites'
      path: '/sites'
      fullPath: '/sites'
      preLoaderRoute: typeof AppSitesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/visits': {
      id: '/_app/visits'
      path: '/visits'
      fullPath: '/visits'
      preLoaderRoute: typeof AppVisitsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/': {
      id: '/_app/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/activity-types': {
      id: '/_app/admin/activity-types'
      path: '/admin/activity-types'
      fullPath: '/admin/activity-types'
      preLoaderRoute: typeof AppAdminActivityTypesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/attendance': {
      id: '/_app/admin/attendance'
      path: '/admin/attendance'
      fullPath: '/admin/attendance'
      preLoaderRoute: typeof AppAdminAttendanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/company': {
      id: '/_app/admin/company'
      path: '/admin/company'
      fullPath: '/admin/company'
      preLoaderRoute: typeof AppAdminCompanyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/configuration': {
      id: '/_app/admin/configuration'
      path: '/admin/configuration'
      fullPath: '/admin/configuration'
      preLoaderRoute: typeof AppAdminConfigurationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/expenses': {
      id: '/_app/admin/expenses'
      path: '/admin/expenses'
      fullPath: '/admin/expenses'
      preLoaderRoute: typeof AppAdminExpensesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/notification-rules': {
      id: '/_app/admin/notification-rules'
      path: '/admin/notification-rules'
      fullPath: '/admin/notification-rules'
      preLoaderRoute: typeof AppAdminNotificationRulesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/security': {
      id: '/_app/admin/security'
      path: '/admin/security'
      fullPath: '/admin/security'
      preLoaderRoute: typeof AppAdminSecurityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/sites': {
      id: '/_app/admin/sites'
      path: '/admin/sites'
      fullPath: '/admin/sites'
      preLoaderRoute: typeof AppAdminSitesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/users': {
      id: '/_app/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/events/': {
      id: '/_app/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof AppEventsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/events/$id': {
      id: '/_app/events/$id'
      path: '/events/$id'
      fullPath: '/events/$id'
      preLoaderRoute: typeof AppEventsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leads-events/': {
      id: '/_app/leads-events/'
      path: '/leads-events'
      fullPath: '/leads-events/'
      preLoaderRoute: typeof AppLeadsEventsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leads/': {
      id: '/_app/leads/'
      path: '/leads'
      fullPath: '/leads/'
      preLoaderRoute: typeof AppLeadsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leads/$id': {
      id: '/_app/leads/$id'
      path: '/leads/$id'
      fullPath: '/leads/$id'
      preLoaderRoute: typeof AppLeadsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/master-data/': {
      id: '/_app/master-data/'
      path: '/master-data'
      fullPath: '/master-data/'
      preLoaderRoute: typeof AppMasterDataIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/master-data/activity-outcomes': {
      id: '/_app/master-data/activity-outcomes'
      path: '/master-data/activity-outcomes'
      fullPath: '/master-data/activity-outcomes'
      preLoaderRoute: typeof AppMasterDataActivityOutcomesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/master-data/addresses': {
      id: '/_app/master-data/addresses'
      path: '/master-data/addresses'
      fullPath: '/master-data/addresses'
      preLoaderRoute: typeof AppMasterDataAddressesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/master-data/categories': {
      id: '/_app/master-data/categories'
      path: '/master-data/categories'
      fullPath: '/master-data/categories'
      preLoaderRoute: typeof AppMasterDataCategoriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/master-data/currencies': {
      id: '/_app/master-data/currencies'
      path: '/master-data/currencies'
      fullPath: '/master-data/currencies'
      preLoaderRoute: typeof AppMasterDataCurrenciesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/master-data/event-types': {
      id: '/_app/master-data/event-types'
      path: '/master-data/event-types'
      fullPath: '/master-data/event-types'
      preLoaderRoute: typeof AppMasterDataEventTypesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/master-data/industries': {
      id: '/_app/master-data/industries'
      path: '/master-data/industries'
      fullPath: '/master-data/industries'
      preLoaderRoute: typeof AppMasterDataIndustriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/master-data/lead-scoring': {
      id: '/_app/master-data/lead-scoring'
      path: '/master-data/lead-scoring'
      fullPath: '/master-data/lead-scoring'
      preLoaderRoute: typeof AppMasterDataLeadScoringRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/master-data/lead-sources': {
      id: '/_app/master-data/lead-sources'
      path: '/master-data/lead-sources'
      fullPath: '/master-data/lead-sources'
      preLoaderRoute: typeof AppMasterDataLeadSourcesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/master-data/lead-statuses': {
      id: '/_app/master-data/lead-statuses'
      path: '/master-data/lead-statuses'
      fullPath: '/master-data/lead-statuses'
      preLoaderRoute: typeof AppMasterDataLeadStatusesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/master-data/opportunity-scoring': {
      id: '/_app/master-data/opportunity-scoring'
      path: '/master-data/opportunity-scoring'
      fullPath: '/master-data/opportunity-scoring'
      preLoaderRoute: typeof AppMasterDataOpportunityScoringRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/master-data/opportunity-stages': {
      id: '/_app/master-data/opportunity-stages'
      path: '/master-data/opportunity-stages'
      fullPath: '/master-data/opportunity-stages'
      preLoaderRoute: typeof AppMasterDataOpportunityStagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/master-data/opportunity-types': {
      id: '/_app/master-data/opportunity-types'
      path: '/master-data/opportunity-types'
      fullPath: '/master-data/opportunity-types'
      preLoaderRoute: typeof AppMasterDataOpportunityTypesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/master-data/payment-terms': {
      id: '/_app/master-data/payment-terms'
      path: '/master-data/payment-terms'
      fullPath: '/master-data/payment-terms'
      preLoaderRoute: typeof AppMasterDataPaymentTermsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/master-data/products': {
      id: '/_app/master-data/products'
      path: '/master-data/products'
      fullPath: '/master-data/products'
      preLoaderRoute: typeof AppMasterDataProductsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/master-data/uom': {
      id: '/_app/master-data/uom'
      path: '/master-data/uom'
      fullPath: '/master-data/uom'
      preLoaderRoute: typeof AppMasterDataUomRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/': {
      id: '/_app/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AppProjectsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$id': {
      id: '/_app/projects/$id'
      path: '/projects/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof AppProjectsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/': {
      id: '/_app/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof AppReportsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/$type': {
      id: '/_app/reports/$type'
      path: '/reports/$type'
      fullPath: '/reports/$type'
      preLoaderRoute: typeof AppReportsTypeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/templates/': {
      id: '/_app/templates/'
      path: '/templates'
      fullPath: '/templates/'
      preLoaderRoute: typeof AppTemplatesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/templates/$id': {
      id: '/_app/templates/$id'
      path: '/templates/$id'
      fullPath: '/templates/$id'
      preLoaderRoute: typeof AppTemplatesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/vendors/$id': {
      id: '/_app/vendors/$id'
      path: '/vendors/$id'
      fullPath: '/vendors/$id'
      preLoaderRoute: typeof AppVendorsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leads-events/events/$id': {
      id: '/_app/leads-events/events/$id'
      path: '/leads-events/events/$id'
      fullPath: '/leads-events/events/$id'
      preLoaderRoute: typeof AppLeadsEventsEventsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leads-events/leads/$id': {
      id: '/_app/leads-events/leads/$id'
      path: '/leads-events/leads/$id'
      fullPath: '/leads-events/leads/$id'
      preLoaderRoute: typeof AppLeadsEventsLeadsIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppActivitiesRoute: typeof AppActivitiesRoute
  AppActivityTimelineRoute: typeof AppActivityTimelineRoute
  AppActivityTypesRoute: typeof AppActivityTypesRoute
  AppAdminControlsRoute: typeof AppAdminControlsRoute
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppAttendanceRoute: typeof AppAttendanceRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppExpensesRoute: typeof AppExpensesRoute
  AppGpsTrackingRoute: typeof AppGpsTrackingRoute
  AppMoreRoute: typeof AppMoreRoute
  AppMyTeamRoute: typeof AppMyTeamRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppPendingApprovalsRoute: typeof AppPendingApprovalsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSitesRoute: typeof AppSitesRoute
  AppVisitsRoute: typeof AppVisitsRoute
  AppAdminActivityTypesRoute: typeof AppAdminActivityTypesRoute
  AppAdminAttendanceRoute: typeof AppAdminAttendanceRoute
  AppAdminCompanyRoute: typeof AppAdminCompanyRoute
  AppAdminConfigurationRoute: typeof AppAdminConfigurationRoute
  AppAdminExpensesRoute: typeof AppAdminExpensesRoute
  AppAdminNotificationRulesRoute: typeof AppAdminNotificationRulesRoute
  AppAdminSecurityRoute: typeof AppAdminSecurityRoute
  AppAdminSitesRoute: typeof AppAdminSitesRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
  AppEventsIdRoute: typeof AppEventsIdRoute
  AppLeadsIdRoute: typeof AppLeadsIdRoute
  AppMasterDataActivityOutcomesRoute: typeof AppMasterDataActivityOutcomesRoute
  AppMasterDataAddressesRoute: typeof AppMasterDataAddressesRoute
  AppMasterDataCategoriesRoute: typeof AppMasterDataCategoriesRoute
  AppMasterDataCurrenciesRoute: typeof AppMasterDataCurrenciesRoute
  AppMasterDataEventTypesRoute: typeof AppMasterDataEventTypesRoute
  AppMasterDataIndustriesRoute: typeof AppMasterDataIndustriesRoute
  AppMasterDataLeadScoringRoute: typeof AppMasterDataLeadScoringRoute
  AppMasterDataLeadSourcesRoute: typeof AppMasterDataLeadSourcesRoute
  AppMasterDataLeadStatusesRoute: typeof AppMasterDataLeadStatusesRoute
  AppMasterDataOpportunityScoringRoute: typeof AppMasterDataOpportunityScoringRoute
  AppMasterDataOpportunityStagesRoute: typeof AppMasterDataOpportunityStagesRoute
  AppMasterDataOpportunityTypesRoute: typeof AppMasterDataOpportunityTypesRoute
  AppMasterDataPaymentTermsRoute: typeof AppMasterDataPaymentTermsRoute
  AppMasterDataProductsRoute: typeof AppMasterDataProductsRoute
  AppMasterDataUomRoute: typeof AppMasterDataUomRoute
  AppProjectsIdRoute: typeof AppProjectsIdRoute
  AppReportsTypeRoute: typeof AppReportsTypeRoute
  AppTemplatesIdRoute: typeof AppTemplatesIdRoute
  AppVendorsIdRoute: typeof AppVendorsIdRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
  AppEventsIndexRoute: typeof AppEventsIndexRoute
  AppLeadsEventsIndexRoute: typeof AppLeadsEventsIndexRoute
  AppLeadsIndexRoute: typeof AppLeadsIndexRoute
  AppMasterDataIndexRoute: typeof AppMasterDataIndexRoute
  AppProjectsIndexRoute: typeof AppProjectsIndexRoute
  AppReportsIndexRoute: typeof AppReportsIndexRoute
  AppTemplatesIndexRoute: typeof AppTemplatesIndexRoute
  AppLeadsEventsEventsIdRoute: typeof AppLeadsEventsEventsIdRoute
  AppLeadsEventsLeadsIdRoute: typeof AppLeadsEventsLeadsIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppActivitiesRoute: AppActivitiesRoute,
  AppActivityTimelineRoute: AppActivityTimelineRoute,
  AppActivityTypesRoute: AppActivityTypesRoute,
  AppAdminControlsRoute: AppAdminControlsRoute,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppAttendanceRoute: AppAttendanceRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppExpensesRoute: AppExpensesRoute,
  AppGpsTrackingRoute: AppGpsTrackingRoute,
  AppMoreRoute: AppMoreRoute,
  AppMyTeamRoute: AppMyTeamRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppPendingApprovalsRoute: AppPendingApprovalsRoute,
  AppProfileRoute: AppProfileRoute,
  AppSitesRoute: AppSitesRoute,
  AppVisitsRoute: AppVisitsRoute,
  AppAdminActivityTypesRoute: AppAdminActivityTypesRoute,
  AppAdminAttendanceRoute: AppAdminAttendanceRoute,
  AppAdminCompanyRoute: AppAdminCompanyRoute,
  AppAdminConfigurationRoute: AppAdminConfigurationRoute,
  AppAdminExpensesRoute: AppAdminExpensesRoute,
  AppAdminNotificationRulesRoute: AppAdminNotificationRulesRoute,
  AppAdminSecurityRoute: AppAdminSecurityRoute,
  AppAdminSitesRoute: AppAdminSitesRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
  AppEventsIdRoute: AppEventsIdRoute,
  AppLeadsIdRoute: AppLeadsIdRoute,
  AppMasterDataActivityOutcomesRoute: AppMasterDataActivityOutcomesRoute,
  AppMasterDataAddressesRoute: AppMasterDataAddressesRoute,
  AppMasterDataCategoriesRoute: AppMasterDataCategoriesRoute,
  AppMasterDataCurrenciesRoute: AppMasterDataCurrenciesRoute,
  AppMasterDataEventTypesRoute: AppMasterDataEventTypesRoute,
  AppMasterDataIndustriesRoute: AppMasterDataIndustriesRoute,
  AppMasterDataLeadScoringRoute: AppMasterDataLeadScoringRoute,
  AppMasterDataLeadSourcesRoute: AppMasterDataLeadSourcesRoute,
  AppMasterDataLeadStatusesRoute: AppMasterDataLeadStatusesRoute,
  AppMasterDataOpportunityScoringRoute: AppMasterDataOpportunityScoringRoute,
  AppMasterDataOpportunityStagesRoute: AppMasterDataOpportunityStagesRoute,
  AppMasterDataOpportunityTypesRoute: AppMasterDataOpportunityTypesRoute,
  AppMasterDataPaymentTermsRoute: AppMasterDataPaymentTermsRoute,
  AppMasterDataProductsRoute: AppMasterDataProductsRoute,
  AppMasterDataUomRoute: AppMasterDataUomRoute,
  AppProjectsIdRoute: AppProjectsIdRoute,
  AppReportsTypeRoute: AppReportsTypeRoute,
  AppTemplatesIdRoute: AppTemplatesIdRoute,
  AppVendorsIdRoute: AppVendorsIdRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
  AppEventsIndexRoute: AppEventsIndexRoute,
  AppLeadsEventsIndexRoute: AppLeadsEventsIndexRoute,
  AppLeadsIndexRoute: AppLeadsIndexRoute,
  AppMasterDataIndexRoute: AppMasterDataIndexRoute,
  AppProjectsIndexRoute: AppProjectsIndexRoute,
  AppReportsIndexRoute: AppReportsIndexRoute,
  AppTemplatesIndexRoute: AppTemplatesIndexRoute,
  AppLeadsEventsEventsIdRoute: AppLeadsEventsEventsIdRoute,
  AppLeadsEventsLeadsIdRoute: AppLeadsEventsLeadsIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  InstallRoute: InstallRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
